### ISSUE TITLE
Blue not working on Python 3.14 because of black 22 dependency

### ISSUE THREAD

**Issue by vgiralt** [grantjenks/blue#116]
My shiny Fedora 43 Linux came with Python 3.14 as a surprise and now I cannot use blue because it relies on black==22.1.0 that uses ast.Str and friends that are not available :-(

Any attempt to run blue ends with: error: cannot format ....py module 'ast' has no attribute 'Str'
